Redirected stderr to stdout to catch error messages from snmpwalk.

diff --git a/check_procurve_loop b/check_procurve_loop
--- a/check_procurve_loop
+++ b/check_procurve_loop
@@ -21,19 +21,19 @@ STATE_WARNING=1
 STATE_CRITICAL=2
 STATE_UNKNOWN=3
 
-PATH=/usr/local/bin:/usr/bin:/bin # Set path
+PATH=/usr/local/bin:/usr/bin:/bin 
 
 TMP_FILE=/tmp/check_procurve_loop.log
 PORTCNT=0
 
-for cmd in snmpwalk awk grep wc [
-do
- if ! `which ${cmd} 1>/dev/null`
- then
- echo "UNKNOWN: ${cmd} does not exist, please check if command exists and PATH is correct"
- exit ${STATE_UNKNOWN}
- fi
-done
+# We require the program snmpwalk, so check that we can find it
+check_cmd=$(which snmpwalk > /dev/null)
+if [[ "$?" -gt 0 ]]
+then
+	# Oh no, can't find snmpwalk!
+	echo "UNKNOWN - unable to locate snmpwalk, please verify that the program is installed and the variable PATH is correct"
+	exit $STATE_UNKNOWN
+fi
 
 # Command line arguments
 if [ $# -lt 4 ]
@@ -54,13 +54,17 @@ do
 done
 
 
-# Check the status
-status=$(snmpwalk -v 2c -O vqe -c $community $host 1.3.6.1.4.1.11.2.14.11.5.1.12.1.5.2.1.1.2)
+# Run snmpwalk and check the status
+status=$(snmpwalk -v 2c -O vqe -c $community $host 1.3.6.1.4.1.11.2.14.11.5.1.12.1.5.2.1.1.2 2>&1)
+retval=$?
+
+if [[ "$retval" -gt 0 ]]
+then
+	echo "UNKNOWN - snmpwalk generated error code $retval, message is '$status'"
+	exit $STATUS_UNKNOWN
+fi
 
 state_crit=0
-state_warn=0
-state_ok=0
-state_unknown=0
 list_ports=""
 for s in $status
 do
@@ -84,9 +88,9 @@ then
 	loopcnt=$(((state_crit - 1)))
 	if [ $loopcnt -eq 1 ]
 	then
-		echo "CRITICAL - found a loop on the following ports: $list_ports"
+		echo "CRITICAL - found a loop on the following ports: $list_ports ($PORTCNT ports checked)"
 	else
-		echo "CRITICAL - found loops on the following ports: $list_ports"
+		echo "CRITICAL - found loops on the following ports: $list_ports ($PORTCNT ports checked)"
 	fi
 	exit $STATE_CRITICAL
 else
@@ -95,4 +99,4 @@ else
 fi
 
 echo "UNKNOWN - should never reach this part!"
-exit $STATE_OK
+exit $STATE_UNKNOWN
